name: Run tests

on:
  pull_request: ~
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  busted:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit"

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install moonscript
          luarocks install luacov
          luarocks install busted

      - name: Report test coverage
        if: ${{ success() }}
        continue-on-error: true
        run: luacov-coveralls -i src -e .luarocks
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
