name: Run tests

on:
  pull_request: ~
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "luajit-2.1.0-beta3" ]

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install moonscript
          luarocks install luacov
          luarocks install --deps-only busted-scm-1.rockspec

      - name: Build ‘busted’ (bootstrap)
        run: |
          luarocks make

      - name: Run ‘busted’ (dogfood)
        # disable project-local path prefixes to force use of system installation
        run: busted --coverage --lpath="" --cpath="" --output=gtest -Xoutput --color

      - name: Report test coverage
        if: ${{ success() && github.repository == 'lunarmodules/busted' }}
        continue-on-error: true
        run: luacov-coveralls -i src -e .luarocks
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
